# import HTTP remote provider
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
import json
import pandas as pd
HTTP = HTTPRemoteProvider()


configfile: "workflow/config/config.yaml"


include: "rules/downloadData.smk"
include: "rules/processMetadata.smk"
include: "rules/process_microarray.smk"
include: "rules/process_rnaseq.smk"
include: "rules/process_mutation.smk"

rule all:
    input:
        metadata = "procdata/metadata.qs",
        preprocessedMicroArray = "procdata/microarray/preprocessedMicroArray.qs",
        mutation_SE = "procdata/mutation/mutation_SE.qs",
        preprocessed = "procdata/rnaseq/preprocessed_rnaseq.qs",
        # preprocessedEXPRESSION = "procdata/expression/preprocessedEXPRESSION.qs",
        # preprocessedCNV = "procdata/cnv/preprocessedCNV.qs",
        # preprocessedMETHYLATION = "procdata/methylation/preprocessedMETHYLATION.qs",
        # preprocessedMUTATION = "procdata/mutation/preprocessedMUTATION.qs",
        # treatmentMetadata = "metadata/treatmentAnnotation.csv",
        # sampleMetadata = "metadata/sampleAnnotation.csv",
        # cellModelPassportsMetadata = "metadata/cellModelPassportsAnnotation.csv",
        # cellmodelpassportsGeneAnnotation = "metadata/cellmodelpassportsGeneAnnotation.csv",



# rule preprocessMETHYLATION:
#     input:
#         methylationData = "rawdata/methylation/METH_CELL_DATA.txt",
#     output:
#         preprocessedMETHYLATION = "procdata/methylation/preprocessedMETHYLATION.qs",
#     threads:
#         10
#     script:
#         "scripts/preprocessMETHYLATION.R"



