PharmacoSet:
  description: "The Genomics of Drug Sensitivity in Cancer (GDSC) is ...
    This dataset contains molecular profiles for 1,000 cancer cell lines, 
    and drug sensitivity data against a wide range of anti-cancer therapeutics."
  url: "https://www.cancerrxgene.org/"

metadata:
  sampleAnnotation: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/Cell_Lines_Details.xlsx"
  treatmentAnnotation: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/screened_compounds_rel_8.5.csv"
  cellmodelpassportsAnnotation: "https://cog.sanger.ac.uk/cmp/download/model_list_20230923.csv"
  cellmodelpassportsGeneAnnotation: "https://cog.sanger.ac.uk/cmp/download/gene_identifiers_20191101.csv"

referenceGenome:
  Gencode:
    build: "GRCh38"
    version: "44"

molecularProfiles:
  microarray:
    description: "Data taken from https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-3610/." 
    metadata_tsv: 
      description: TODO::(add description)
      url: "https://www.ebi.ac.uk/biostudies/files/E-MTAB-3610/E-MTAB-3610.tsv"
    metadata_srdf: 
      description: TODO::(add description)
      url: "https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/610/E-MTAB-3610/Files/E-MTAB-3610.sdrf.txt"
    metadata_json: 
      description: TODO::(add description)
      url: "https://ftp.ebi.ac.uk/biostudies/fire/E-MTAB-/610/E-MTAB-3610/Files/raw-data_filelist.json"
    processed: 
      description: "RMA normalised basal expression profiles for all the cell-lines."
      reference: "https://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources/Home.html"
      url: "https://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources///Data/preprocessed/Cell_line_RMA_proc_basalExp.txt.zip"
  
  rnaseq:
    rawdata: 
      description: "Data available from EGA under accession EGAD00001001357. 466 samples. 
        Access to raw cram files requires DAC approval. "
      url: "https://ega-archive.org/datasets/EGAD00001001357"
    processed:
      description: "Read counts, TPM & FPKM-values for all sequenced models 
        including cell lines and organoids."
      url: "https://cog.sanger.ac.uk/cmp/download/rnaseq_all_20220624.zip"

  cnv:
    WES_CNV: 
      description: TODO::(add description)
      url: "https://cog.sanger.ac.uk/cmp/download/WES_pureCN_CNV_genes_20221213.zip"

  mutation:
    WGS_VCF: 
      description: "Caveman and Pindel processed VCFs with cancer driver annotation."
      url: "https://cog.sanger.ac.uk/cmp/download/mutations_wgs_vcf_20221123.zip"
    WES_VCF: 
      description: "Caveman and Pindel processed VCFs with cancer driver annotation."
      url: "https://cog.sanger.ac.uk/cmp/download/mutations_wes_vcf_20221010.zip"
    SUMMARY: 
      description: "A list of all mutations present in all sequenced models."
      url: "https://cog.sanger.ac.uk/cmp/download/mutations_all_20230202.zip"
    Genes_Metadata:
      description: "The cancer driver gene list used by the Cell Model Passports"
      url: "https://cog.sanger.ac.uk/cmp/download/driver_mutations_20221208.csv"

  methylation:
    description: "Not implemented yet."
    processed: 
      description: TODO::(add description)
      url: 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE68nnn/GSE68379/suppl/GSE68379_Matrix.processed.txt.gz'
    signalIntensity: 
      description: TODO::(add description)
      url: 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE68nnn/GSE68379/suppl/GSE68379_Matrix.Signal.Intensities.txt.gz'
    meth_cell_data: 
      description: TODO::(add description)
      url: "https://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources/Data/preprocessed/methylation/METH_CELL_DATA.txt.zip"
    sample_mapping_metadata:
      description: TODO::(add description)
      url: "https://www.cancerrxgene.org/gdsc1000/GDSC1000_WebResources//Data/otherAnnotations/methSampleId_2_cosmicIds.xlsx"

  fusion:
    gene_fusions:
      description: TODO::(add description)
      url: "https://cog.sanger.ac.uk/cmp/download/Fusions_20230725.zip"


treatmentResponse:
  8.2:
    date: "25Feb20"

    GDSC1:
      rawdata:
        description: "The raw data for the GDSC1 release 8.2 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.2/GDSC1_public_raw_data_25Feb20.csv"
      processed:
        description: "The processed data for the GDSC1 release 8.2 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.2/GDSC1_fitted_dose_response_25Feb20.xlsx"
    GDSC2:
      rawdata:
        description: "The raw data for the GDSC2 release 8.2 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.2/GDSC2_public_raw_data_25Feb20.csv"
      processed:
        description: "The processed data for the GDSC2 release 8.2 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.2/GDSC2_fitted_dose_response_25Feb20.xlsx"
  8.4:
    date: "24Jul22"
    metadata:
      sampleMetadata: 
        description:
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/Cell_Lines_Details.xlsx"
      treatmentMetadata:
        description:
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/screened_compounds_rel_8.4.csv"
    GDSC1:
      rawdata:
        description: "The raw data for the GDSC1 release 8.4 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/GDSC1_public_raw_data_24Jul22.csv"
      processed:
        description: "The processed data for the GDSC1 release 8.4 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/GDSC1_fitted_dose_response_24Jul22.xlsx"
    GDSC2:
      rawdata:
        description: "The raw data for the GDSC2 release 8.4 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/GDSC2_public_raw_data_24Jul22.csv"
      processed:
        description: "The processed data for the GDSC2 release 8.4 is available from the GDSC website."
        url: "https://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/release-8.4/GDSC2_fitted_dose_response_24Jul22.xlsx"
  8.5: 
    date: "27Oct23"
    metadata:
      sampleMetadata: 
        description:
        url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/Cell_Lines_Details.xlsx"
      treatmentMetadata:
        description:
        url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/screened_compounds_rel_8.5.csv"
    GDSC1:
      rawdata:
        description: "The raw data for the GDSC1 release 8.5 is available from the GDSC website."
        url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/GDSC1_public_raw_data_27Oct23.csv"
      processed:
        description: "The processed data for the GDSC1 release 8.5 is available from the GDSC website."
        url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/GDSC1_fitted_dose_response_27Oct23.xlsx"
    GDSC2:
      rawdata:
        description: "The raw data for the GDSC2 release 8.5 is available from the GDSC website."
        url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/GDSC2_public_raw_data_27Oct23.csv"
      processed:
        description: "The processed data for the GDSC2 release 8.5 is available from the GDSC website."
        url: "https://cog.sanger.ac.uk/cancerrxgene/GDSC_release8.5/GDSC2_fitted_dose_response_27Oct23.xlsx"

